version: "3.3"

services:

  api:
    image: nginx:stable-alpine
    container_name: xamlinx_api
    volumes:
      - ./source:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    ports:
      - 80:80

  mysql:
    image: mysql:8.0.26
    container_name: xamlinx_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  php:
    build:
      context: ./docker/api/.
    container_name: xamlinx_php
    volumes:
      - ./source:/var/www/html:delegated
    ports:
      - 9000:9000

  composer:
    image: composer:latest
    container_name: xamlinx_composer
    volumes:
      - ./source:/var/www/html
    working_dir: /var/www/html
    command: install
    depends_on:
      - php
    entrypoint: ["composer", "--ignore-platform-reqs"]

  spark:
    build:
      context: ./docker/api/.
    container_name: xamlinx_spark
    volumes:
      - ./source:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/spark"]

  npm:
    image: node:lts-alpine
    container_name: xamlinx_npm
    volumes:
      - ./source:/var/www/html
    working_dir: /var/www/html
    environment: 
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    command: install
    entrypoint: ['npm']

volumes:
  mysql: